main: insertion_sort.o random.o
	gcc -Wall insertion_sort.o random.o -std=c99 -o main

insertion_sort.o: insertion_sort.c
	gcc -Wall -c insertion_sort.c -std=c99

random.o: random.c
	gcc -Wall -c random.c -std=c99
