main: selection_sort.o random.o
	gcc -Wall selection_sort.o random.o -std=c99 -o main

selection_sort.o: selection_sort.c
	gcc -Wall -c selection_sort.c -std=c99

random.o: random.c
	gcc -Wall -c random.c -std=c99
